# General settings

# Minimum age of cached update state before it will be refreshed
cache_min_age_minutes = 30
# Custom output format - use with `--output-format=custom`
# Available variables for custom_format:
#     - $available_updates:      Comma-separated list of available updates
#     - $last_update:            Date and time of last time siun checked for updates in ISO format
#     - $matched_criteria:       Comma-separated names of matched criteria
#     - $matched_criteria_short: Comma-separated matched criteria, shortened to 2 characters
#     - $score:                  Sum weight of matched criteria
#     - $status_text:            Text representation of update status, e.g. "Updates available"
#     - $update_count:           Number of available updates
custom_format = "$status_text: $available_updates"
# State file location
state_file = "$XDG_STATE_HOME/siun/state.json"

[update_provider]
# Available providers: [ pacman | generic ]
name = "pacman"

[[v2_thresholds]]
# Unique name
name = "critical"
# Minimum sum of criteria weights to consider this threshold exceeded
score = 3
# Color for `fancy` output format; optional
color = "red"
# Custom text for output
text = "Updates required"

[[v2_thresholds]]
name = "warning"
score = 2
color = "yellow"
text = "Updates recommended"

[[v2_thresholds]]
name = "available"
score = 1
color = "green"
text = "Updates available"

# Settings for check criteria - these will determine the urgency of your package updates
[[v2_criteria]]
name = "available"
weight = 1

[[v2_criteria]]
name = "pattern"
weight = 1
pattern = "^archlinux-keyring$|^linux$|^pacman.*$"

[[v2_criteria]]
name = "count"
weight = 1
count = 15

# Settings for desktop notification
[notification]
# Notification body, supports the same format placeholders as the `custom_format` setting
message = "$available_updates"
# Notification title, supports the same format placeholders as the `custom_format` setting
title = "$status_text"
# Notification urgency ["low"|"normal"|"critical"]
urgency = "normal"
# Notification timeout, `0` means no timeout
timeout = 10000
# Notification icon, can be either icon name or path
icon = "siun-icon"
# Minimum threshold for notification to show ["available"|"warning"|"critical"]
threshold = "available"
