# General settings
# Command which returns list of available updates
cmd_available = "pacman -Quq; if [ $? == 1 ]; then :; fi" # pacman returns exit code 1 if there are no updates
# Weight required to consider updates to be of `available`, `warning`, or `critical` level
thresholds = { available = 1, warning = 2, critical = 3 }
# Minimum age of cached update state before it will be refreshed
cache_min_age_minutes = 30
# Custom output format - use with `--output-format=custom`
# Available variables for custom_format:
#     - $available_updates:      Comma-separated list of available updates
#     - $last_update:            Date and time of last time siun checked for updates in ISO format
#     - $matched_criteria:       Comma-separated names of matched criteria
#     - $matched_criteria_short: Comma-separated matched criteria, shortened to 2 characters
#     - $score:                  Sum weight of matched criteria
#     - $status_text:            Text representation of update status, e.g. "Updates available"
#     - $update_count:           Number of available updates
custom_format = "$status_text: $available_updates"
# State file location
state_file = "$XDG_STATE_HOME/siun/state.json"

# Settings for check criteria - these will determine the urgency of your package updates
[criteria]
# Setting for `critical` criterion
critical_pattern = "^archlinux-keyring$|^linux$|^pacman.*$"
# Weight the criterion contributes to urgency score
critical_weight = 1 # if set to `0` criterium won't be checked
# Setting for `count` criterion
count_threshold = 10
# Setting weight to 0 disables check
count_weight = 1
# Setting for `last_pacman_update` criterion
last_pacman_update_age_hours = 618 # 7 days
last_pacman_update_weight = 1

# Settings for desktop notification
[notification]
# Notification body, supports the same format placeholders as the `custom_format` setting
message = "$available_updates"
# Notification title, supports the same format placeholders as the `custom_format` setting
title = "$status_text"
# Notification urgency ["low"|"normal"|"critical"]
urgency = "normal"
# Notification timeout, `0` means no timeout
timeout = 10000
# Notification icon, can be either icon name or path
icon = "siun-icon"
# Minimum threshold for notification to show ["available"|"warning"|"critical"]
threshold = "available"
