# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.13"]

    steps:
    - uses: actions/checkout@v4
    - uses: eifinger/setup-rye@v4
      with:
        enable-cache: true
    - name: Select Python toolchain and install dependencies
      run: |
        rye pin ${{ matrix.python-version }}
        rye sync --no-lock
    - name: Lint
      run: |
        rye lint
    - name: Test
      run: |
        rye test
