# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Python application
on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
      - release/*
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.13"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@6b9c6063abd6010835644d4c2e1bef4cf5cd0fca # v6.0.1
        with:
          version: 0.7.5
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-dependency-glob: uv.lock
      - name: Install system dependencies
        run: |
          sudo apt install -y build-essential libpython3-dev libdbus-1-dev libglib2.0-dev
      - name: Install
        run: |
          uv sync --all-extras --dev
      - name: Lint
        run: |
          uv run --frozen ruff check src/
      - name: Test
        run: |
          uv run --frozen coverage run -m pytest
      - name: Generate coverage XML
        run: |
          uv run --frozen coverage xml
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5.4.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
